const fs = require('fs');
const path = require('path');

// Paths
const packageJsonPath = path.join(__dirname, '../package.json');
const versionFilePath = path.join(__dirname, '../src/environments/version.ts');
const envDir = path.join(__dirname, '../src/environments');

// --- Setup ---
// 1. Ensure environments dir exists
if (!fs.existsSync(envDir)){
    fs.mkdirSync(envDir, { recursive: true });
}

// 2. Read package.json
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

// Get increment type from args (patch, minor, major)
const type = process.argv[2] || 'patch';
const currentVersion = packageJson.version;
let [major, minor, patch] = currentVersion.split('.').map(Number);

// 3. Logic to increment
switch (type) {
    case 'major':
        major++;
        minor = 0;
        patch = 0;
        break;
    case 'minor':
        minor++;
        patch = 0;
        break;
    case 'patch':
    default:
        patch++;
        break;
}

const newVersion = `${major}.${minor}.${patch}`;

// 4. Update package.json
packageJson.version = newVersion;
fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');

// 5. Generate Angular version file
const versionFileContent = `// This file is auto-generated by scripts/bump-version.js
export const APP_VERSION = '${newVersion}';
export const BUILD_DATE = '${new Date().toISOString()}';
`;

fs.writeFileSync(versionFilePath, versionFileContent);

// Thay thế thông báo có màu bằng thông báo cơ bản
console.log(`✅ Version bumped from ${currentVersion} to ${newVersion} (${type})`);
console.log(`Generated ${versionFilePath}`);