const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Paths
const packageJsonPath = path.join(__dirname, '../package.json');
const versionFilePath = path.join(__dirname, '../src/environments/version.ts');
const envDir = path.join(__dirname, '../src/environments');

// --- Setup ---
// 1. Ensure environments dir exists
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

// 2. Read package.json
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

// Get increment type from args (patch, minor, major)
const type = process.argv[2] || 'patch';
const currentVersion = packageJson.version;
let [major, minor, patch] = currentVersion.split('.').map(Number);

// 3. Logic to increment
switch (type) {
  case 'major':
    major++;
    minor = 0;
    patch = 0;
    break;
  case 'minor':
    minor++;
    patch = 0;
    break;
  case 'patch':
  default:
    patch++;
    break;
}

const newVersion = `${major}.${minor}.${patch}`;

// 4. Get Git Hash (New logic to fix the error)
let gitHash = '';
try {
  gitHash = execSync('git rev-parse --short HEAD').toString().trim();
} catch (e) {
  console.warn('Warning: Could not retrieve Git hash.');
}

// 5. Update package.json
packageJson.version = newVersion;
fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');

// 6. Generate Angular version file with GIT_HASH
const versionFileContent = `// This file is auto-generated by scripts/bump-version.js
export const APP_VERSION = '${newVersion}';
export const GIT_HASH = '${gitHash}';
export const BUILD_DATE = '${new Date().toISOString()}';
`;

fs.writeFileSync(versionFilePath, versionFileContent);

console.log(
  `✅ Version bumped from ${currentVersion} to ${newVersion} (${type})`
);
console.log(`✅ Git Hash: ${gitHash || 'N/A'}`);
console.log(`Generated ${versionFilePath}`);
