import {
  Component,
  inject,
  ElementRef,
  ViewChild,
  effect,
  HostListener,
  ChangeDetectionStrategy,
  NgZone,
  AfterViewInit,
  OnDestroy,
  TrackByFunction
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { LlmService, ChatMessage } from '../../core/services/llm.service';
import { MarkdownPipe } from '../../shared/pipes/markdown.pipe';

@Component({
  selector: 'app-ai-chat',
  standalone: true,
  imports: [CommonModule, FormsModule, MarkdownPipe],
  templateUrl: './ai-chat.component.html',
  styleUrls: ['./ai-chat.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AiChatComponent implements AfterViewInit, OnDestroy {
  public readonly llmService = inject(LlmService);
  private readonly ngZone = inject(NgZone);
  private readonly router = inject(Router);

  public userInput = '';
  private isNearBottom = true;
  private scrollCleanup?: () => void;

  @ViewChild('scrollContainer') private scrollContainer!: ElementRef<HTMLDivElement>;

  // TrackBy function for better list rendering performance
  public readonly trackByMessage: TrackByFunction<ChatMessage> = (index, msg) => {
    return msg.id;  // Use unique ID instead of timestamp
  };

  constructor(private elementRef: ElementRef) {
    effect(() => {
      // Subscribe to messages changes
      const msgs = this.llmService.messages();
      if (this.isNearBottom && msgs.length > 0) {
        requestAnimationFrame(() => this.scrollToBottom());
      }
    });
  }

  ngAfterViewInit(): void {
    this.setupEfficientScrollListener();
  }

  ngOnDestroy(): void {
    this.scrollCleanup?.();
  }

  private setupEfficientScrollListener(): void {
    if (!this.scrollContainer) return;

    const el = this.scrollContainer.nativeElement;

    this.ngZone.runOutsideAngular(() => {
      const handler = () => {
        const threshold = 50;
        const position = el.scrollTop + el.clientHeight;
        const height = el.scrollHeight;
        this.isNearBottom = position >= height - threshold;
      };

      el.addEventListener('scroll', handler, { passive: true });
      this.scrollCleanup = () => el.removeEventListener('scroll', handler);
    });
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    const target = event.target as HTMLElement;
    const isToggleButton = target.closest('.ai-fab') || target.closest('.ai-trigger-btn');

    if (this.llmService.isOpen() && !this.elementRef.nativeElement.contains(target) && !isToggleButton) {
      this.closeChat();
    }
  }

  // Handle Router Links generated by AI markdown
  @HostListener('click', ['$event'])
  onChatClick(event: MouseEvent): void {
    const target = event.target as HTMLElement;
    const anchor = target.closest('a');

    if (anchor) {
      const href = anchor.getAttribute('href');
      // Internal link navigation
      if (href?.startsWith('/')) {
        event.preventDefault();
        this.router.navigateByUrl(href);
      }
    }
  }

  closeChat(): void {
    this.llmService.isOpen.set(false);
  }

  handleMainButton(): void {
    if (this.llmService.isGenerating()) {
      // Use the proper stop method that aborts the fetch request
      this.llmService.stopGeneration();
    } else {
      this.onSend();
    }
  }

  async onSend(): Promise<void> {
    const text = this.userInput.trim();
    if (!text) return;

    this.userInput = '';
    this.isNearBottom = true;
    this.scrollToBottom();

    await this.llmService.sendMessage(text);
  }

  shouldShowThinking(): boolean {
    if (!this.llmService.isGenerating()) return false;

    const msgs = this.llmService.messages();
    if (msgs.length === 0) return true;

    const lastMsg = msgs[msgs.length - 1];
    return lastMsg.role === 'assistant' && !lastMsg.content;
  }

  // Context usage level for UI indicator
  getContextLevel(): 'low' | 'medium' | 'high' {
    const usage = this.llmService.contextUsage();
    if (usage >= 80) return 'high';
    if (usage >= 50) return 'medium';
    return 'low';
  }

  private scrollToBottom(): void {
    try {
      if (this.scrollContainer) {
        const el = this.scrollContainer.nativeElement;
        el.scrollTop = el.scrollHeight;
      }
    } catch (err) {
      // Ignore scroll errors
    }
  }
}